### ISSUE TITLE
hello，What does the bypass_ node parameter mean? Is it an proxy? How to set this parameter?

### ISSUE THREAD

**Issue by lean-wang** [acheong08/ChatGPT-lite#10]

**Comment by lean-wang** [comment]
hello，What does the bypass_ node parameter mean? Is it an proxy? How to set this parameter?

**Comment by acheong08** [comment]
Leave it alone. There is only one bypass_node available right now

**Comment by acheong08** [comment]
Not open source as said in the readme

**Comment by lean-wang** [comment]
OK，thankyou！
