### ISSUE TITLE
Error:  You are using a old version of the client pawan

### ISSUE THREAD

**Issue by YIDE721** [acheong08/ChatGPT-lite#15]
Error: You are using a old version of the client. Please update to the latest version. Join our Discord server if you need help. https://discord.pawan.krd

When running, I got this error.

**Comment by acheong08** [comment]
Lol he's trying to block others from using his API. I will fix this immediately

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT-lite/releases/tag/0.0.5

lol
