### ISSUE TITLE
Hello, we have launched three ChatGPT text detectors ! 🎉

### ISSUE THREAD

**Issue by izhx** [acheong08/ChatGPT-lite#16]
github project page: 
https://github.com/Hello-SimpleAI/chatgpt-comparison-detection

Could you add to your list if possible? Many thanks! ❤️

**Comment by acheong08** [comment]
Looks interesting. Added

**Comment by acheong08** [comment]
Can you explain the difference between GLTR and PPL?

**Comment by acheong08** [comment]
It's pretty accurate though

**Comment by izhx** [comment]
> Can you explain the difference between GLTR and PPL? It's a bit confusing

[GLTR](https://aclanthology.org/P19-3019) Test 2 uses GPT2 to predict token rank top-k buckets, top 10, 10-100, 100-1000, 1000+.

Specifically, for each word (token) in the give text, we compute its predicted probability rank in the hole GPT2 vocabulary. And then group all token ranks into four buckets: top 10, 10-100, 100-1000, 1000+.

For a 10 words sentence of human, the result could be [1, 1, 3, 6]. 10 words of Language models could be [7, 1, 1, 1], which always generate most high prob tokens.

Visualization ref to [the demo of ACL 19](http://gltr.io/dist/index.html) ~

We use this counter (e.g., [1, 1, 3, 6]) to train a logistic regression model.

---
For PLL, we use the feature array like [`text_ppl`, `avg_sentence_ppl`, `max_sentence_ppl`, `sentence_ppl_std`, ...].
And also train a logistic regression model.

**Comment by izhx** [comment]
We are active on twitter as well ~
https://twitter.com/hsin_zhang/status/1613175623803113473
