### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by axsddlr** [acheong08/ChatGPT-lite#3]
# Issue
 Running code as shown in example

# Screenshot
[<img alt="alt_text" src="https://i.imgur.com/7YnX9FY.png" />](https://i.imgur.com/7YnX9FY.png)

**Comment by acheong08** [comment]
Happens sometimes. Need to try a few times

**Comment by FRCassarino** [comment]
Tried 10 times, got the same connection error every time.

**Comment by axsddlr** [comment]
> Happens sometimes. Need to try a few times

tried multiple times, still same result

**Comment by otherland** [comment]
Hi, I'm also unable to connect. Tested multiple tokens now.

**Comment by acheong08** [comment]
@PawanOsman might have done something to his API. Ask him on Discord https://discord.com/invite/RvBkdcYUrH

**Comment by FRCassarino** [comment]
I can't connect anymore either (used to work)

**Comment by acheong08** [comment]
Works now

**Comment by acheong08** [comment]
ChatGPT is down
![image](https://user-images.githubusercontent.com/36258159/210459783-71f64613-8e46-465c-8d03-03fac79ebc2b.png)

**Comment by axsddlr** [comment]
even with new update, still cannot connect, ill likely say im abandoning attempts with this project

**Comment by acheong08** [comment]
Yeah. Because it is hosted by someone else, I can't really help with the connection side. Sorry for the time wasted.

**Comment by axsddlr** [comment]
> Yeah. Because it is hosted by someone else, I can't really help with the connection side. Sorry for the time wasted.

not your fault, main reasons why i like to self run api's, people who host them never usually have the resources to keep them running

**Comment by acheong08** [comment]
Yeah. Closed source APIs are both a privacy nightmare and impossible to rely on.

I think the author of the API also implemented cloudflare 🤔 which might be blocking IPs.

**Comment by axsddlr** [comment]
> Yeah. Closed source APIs are both a privacy nightmare and impossible to rely on.
> 
> I think the author of the API also implemented cloudflare 🤔 which might be blocking IPs.

yeap i went to original dev and cant pull get requests from insomnia because of cloudflare, easily done on web browser tho

**Comment by acheong08** [comment]
I was poking around his server and I think the bypass is as follows:
1. In his cloudflare configuration, socket connections are allowed without protections
2. He whitelists his server IP which gets a cf_clearance without a challenge
3. User makes a request → his server (which asks for a cf_clearance from his own website) → Use the cf_clearance for OpenAI.

cf_clearance might be shared. Need to try it out

**Comment by axsddlr** [comment]
> I was poking around his server and I think the bypass is as follows:
> 
> 1. In his cloudflare configuration, socket connections are allowed without protections
> 2. He whitelists his server IP which gets a cf_clearance without a challenge
> 3. User makes a request → his server (which asks for a cf_clearance from his own website) → Use the cf_clearance for OpenAI.
> 
> cf_clearance might be shared. Need to try it out

sounds about right

**Comment by acheong08** [comment]
It seems cf_clearance isn't completely shared. There might be other cookies that need to match up. Not completely sure which ones. Testing out different ones

**Comment by acheong08** [comment]
Edit: It works occasionally. Sometimes a shared cf_clearance works, other times it doesn't. Not sure what the exact reason is

**Comment by axsddlr** [comment]
> Edit: It works occasionally. Sometimes a shared cf_clearance works, other times it doesn't. Not sure what the exact reason is

lol ill go back to your go server implement

**Comment by PawanOsman** [comment]
> I was poking around his server and I think the bypass is as follows:
> 1. In his cloudflare configuration, socket connections are allowed without protections
> 2. He whitelists his server IP which gets a cf_clearance without a challenge
> 3. User makes a request → his server (which asks for a cf_clearance from his own website) → Use the cf_clearance for OpenAI.
> 
> cf_clearance might be shared. Need to try it out

No this is not what i do, and cf_clearance is not shared between websites 😅

And for connection problem, Python implementations are unofficial and they generated by ChatGPT as i mentioned in Discord, and also this package is wrote based on my package which is generated by ChatGPT, you need to use NoddJs or c# package they are official packages for my server.

and for reliability, i own a Server hosting company, we created a pool of servers to run this API, and my goal for close-sourcing the back end is to not being patched by OpenAI, currently over 50 socket users using it at the same time without issue

and if you say why you do it for free? The answer is simple, i like doing everything as a service for free, i have many other APIs for free that they are running for years

**Comment by acheong08** [comment]
> No this is not what i do, and cf_clearance is not shared between websites sweat_smile

I was able to swap the cf_clearance around and have it load without challenges (although highly unreliable). Might look into that

**Comment by acheong08** [comment]
> package is wrote based on my package which is generated by ChatGPT

I wrote it before you released your package and it was translated from your NodeJS package. I do recommend using C# for better reliability though

**Comment by acheong08** [comment]
> 
and if you say why you do it for free? The answer is simple, i like doing everything as a service for free, i have many other APIs for free that they are running for years

Thank you

**Comment by PawanOsman** [comment]
> > package is wrote based on my package which is generated by ChatGPT
> 
> I wrote it before you released your package and it was translated from your NodeJS package. I do recommend using C# for better reliability though

NodeJS is best because the server is also NodeJs and both is using official socket.io server and client 

The C# is also stable and didn't have any problems

**Comment by acheong08** [comment]
Refer to @PawanOsman for information if you encounter this issue. Closing
