### ISSUE TITLE
Some session_tokens throw an "incorrect padding error"

### ISSUE THREAD

**Issue by FRCassarino** [acheong08/ChatGPT-lite#6]
Some of the session tokens that get generated for my open ai user, when used with this API, result in this error throwing:

"
Traceback (most recent call last):
  File "/Users/frcassarino/Documents/GitHub/ChatGPT-PR-Reviewer/request_handler.py", line 156, in generate_review
    print(loop.run_until_complete(chatbot.ask(file.replace("\n", ""))))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/frcassarino/Library/Python/3.8/lib/python/site-packages/ChatGPT_lite/ChatGPT.py", line 80, in ask
    if self.auth is None or not self.validate_token(self.auth):
  File "/Users/frcassarino/Library/Python/3.8/lib/python/site-packages/ChatGPT_lite/ChatGPT.py", line 116, in validate_token
    parsed = json.loads(base64.b64decode(token.split('.')[1]).decode())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_webhook.py", line 520, in <module>
    request_handler.handle_webhook(mock_body)
  File "/Users/frcassarino/Documents/GitHub/ChatGPT-PR-Reviewer/request_handler.py", line 51, in handle_webhook
    review = mock_review if config["should_mock_api_call"] else self.generate_review(
  File "/Users/frcassarino/Documents/GitHub/ChatGPT-PR-Reviewer/request_handler.py", line 166, in generate_review
    raise Exception(e)
Exception: Incorrect padding"

Here's an example of one that repros:
"eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..7OOnrcGmlPibK3sT.wj-iqrCRYOtnLgp6lGxTDnXMXLaiR5vDMrNCYnEBPI6ZweJNHOMfi51Phe-5MX4GszkCdszeRBiR5HBy4ITp59MAZ-qrTkoj75BzD4SLBhKnc5RM85wWvHry9ETY7HFRmY9QvezY5KFG58YzLpaWeZ4j7Ac9i_GdjE-gYjuPmaVGKstJmnFSw_3HaMhU6LnjcBI3Ftqd8R50tlSpPkWHv5l7mvdEwqPJV8r1A4R2okNhTfH45huy6wYRvXVeD0BS_CumphIhsAxAKpVTjN8QUGxHETTRtpZKvJ40Pr1IOBMoPPvUijiXE9Pt2zCoPSQqhKIg28r_CbcPJVYFMe0lTBuSW2dT8l0MF-7UmPHCTRx60__T19A-up3Fy7P9BixiP8A9Xwjy2mubHUJq9RrD6sAFAm2zE5fJLPcN9UY_mO1L5GZrUxJ80oJskyCytPC4ZIbyalO7U0cRtqxu1ynatNnxMbcLTfnWtRnZ7A8elmuSTtRxfz4QlKV4_Won0FlAogTFhKuE5Yq4iH3x8tDHRNvgmFeWpOGBe5aqn-qcn8v5z2F06WVeE9DzSsD0ln-b85hGbFwEgnZwrTfaai8b0zRcI_awl_nPPMxtK7I_DJXvLcZ4uTTLIF7ihjDcTiRXjyc1LMZwyra6SOZDs50_18aIDIDYJ4ej073Wg7r-onYg3iuStza_35B3y653X0LkeBJr4Q1LVuwD5KnHD6u7sQmo97uxoGP5koegkC_n53ebw9ErMEZY_bFiFX3OGU1uoWqgdsw4UQbwQUjb6EuXuWXWfMy1iMTNOcCThasPNi8DR5zg2iyn7-L83kb5QJuuFhVPgSTVycd61sWzhf14hzisVvz-p65Uqw3obUvKHh_fmqfUdDM50Ef7506qMiYkwXw9PP0UlcPAaDe3BH3dcEUxR4iCUUZ6KZdAc-0-jyp9iaB9bD9jglAoJGyrOv7tBS3_OYr3u0tyPlDb-4TvLXhCDZ83bm7TvqQYRnhHjXJAlXnxedgsRFnF5MS2cO_rLfAs7aan6szjdSEDNOJzwYhaOvToctB7w_Rw-1pZFkDGECU_o_Ewp_g2QCo8f-pBrdHZl4WGeQ5mjBrFSbBo1YczLm1E3oCroSvAnZpuj2NWDoQ56H1PGTsRbAZll8PeiCP1JbgSBXaYe6gjPiftzhHAxdebsVeQAZ0umPsveA5tTJsMUb_kMGxJ0Ns2plSOMCou36JilrqW-aU-vxo7PF2u0h55k2XZG4ubRnCGPj-r3CT_SeMwmQ_m5X-4GHfsulE_znZ1UlhoIrnfOwqtIvlCFPaRLD94lhvzIn4BiPvF1Bcj2wl0Cw_KkKBiql4KMp8ikCGyzcj6LNWElgR5SZRr5IJRidMpTgr0mT56oLqgp5YpPL-EsQBJpwaZ2YXZoKDDeBtNg_7CQyGy7rXg5fl_oPhZKtp25YAMOGBkSkFkvlCuZTb1-iRUE4oOHKgDCZX0cfmiu3TvYNknpBzfERvsgpd3t2lW1dXK23Z1zDr1PaHJKBQXAIAFt5oAqFQY1dYEQShFG3Q9y-rB-oFjZaWeMCF9Q4A8RYs5OPU4Yxs_LYtwwdITFvXPXpg_EiY3Q1y_CdXYsqfOtNSnpwXWzoHm_wLJVxOvp3Y_M8JvBrcJylC7VkSaD-pqr3QzygazemDw45ebyz3pZYHt--jPE-yxysTPxs_oqTqX6dOcKibdZeDhwspeYLJXIaM4cKIlZZiFsh60Io3uC9YJdnmZ6ceoZ8OEETmtd7eicNX4rGuA8I4mU5vxXu9EuuEPwKvJdbgnDTonZkgBk1aCriXI5iyFbJN9kXWCqSSMJOsqI3rt-3GfYNzNtIxpJlN_Os5A8bS6sJNwszzLaH0WkKbac05elTon91YvmYnE55IaAkiMiyj1_G_CWaXBsmZAaaKjrWF_-WQJC5EX1n70OXmY9qtnOGxkqN5XRLKAjcnufdoc4N4kCVlEouAfqQT4FuGslC4l4hc8oykOqmOkA8xdKkepXSXcVEyZk9rTvUBqopERskgS-p0E-6WV86djZawTPmfGztqJWkaQyZOKajcGLrpPP8_If3iAfG8ofMDkCxY4LtlzDy6OQVOiNqsWVD3PrynE7kPowcWiodfCBFzd1tL1nkMiMqEMufsUnB6S6VtNG-S-Gn1XFKKZasJ6qsTjuQ1DAvqC-VY_UviG8EYMLHnJus1UT_qqDruqEacn6gKq93kbECp4Fjjo_lF5Fxhg1VJRGFWePcf3O0U3XFVXPhlHzWVAvUih9fgVuFAGuLOzpaHv3DYS6MXHRIn1CjTdnO9rXscY1psnTDHLhs94KEc8-js_ojoq4YBEVBI-uglMXgGuIjJwtjvSHdHczBNIGuq7ohSU_QEo7I6MlCnQkA.jdjapdnM4yaTzHnlUPj7qw"

Here's an example of one that doesn't repro:

"eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..GkYrC_SOnK6xRo4T.73IoAzdBRs4xCoTA2BVEpkfV64fYxQbBNx8xsDhk8TaMNssoTK1hcMrZFG8un8rtQtPUIro7JVkMTMFuO0hW3Q9KhkB5oqFGg1THsEv_89UCgFvULVSBzjrbNXbdi5ihgz_TpE4BqLC7_MSLTro5k8dIvq00n8-oMspqwTeaWAt4F6dXt0pY-PYvXxd8p0MZtCihfgehgyKKj7xVwitx6JZyaAmCuUXnauw2B6AzxH98nml5FLhPMltZam5p1ICHdfMpsRnwTt6sASKGqr-Tg8kQCeNXSzdQnMDFySEB4rcRpvK9xEJmUBt2CowhWVaIVUBk_uvmCLgD5VfwBJ9T8xGeljW2VpWiZfPbjFOKTHbqjZbu6iEoqfCsPojPYzL1G0o1PfAQ0w1YpLprDei_yTcxkC7LFY9tV470LzTRl-LQ82ZmjnsGOn7LYmvv61bqkl9IW3VwJ6N2HKjmPLGolsR4vk9axK1O_B98OBivxRNugvFhtagamzTZVR7qNyB_M97PcnQpPrFeC3o-ij_wyJoWD2opl9dFLRzUROtAyDQbYXyfP1DwekL5UXqKG1-2asIwaur04g9LUeRbWtelWuYt4Ix4il6v2W22t574pSfB7u0B3MLklwKictSVTErorQrAQdx7XsJSQPM2wL2VxV0Dw4I3MECluIIB_-RfWyUDRn36JZ_nm6kOf0SwR_JkQg_i5cCiIDjx6HZbNz_XrWqCpYZAEtXHxfuXDYyMPCb4sN9GuI1hOiL_NPzcrasVuHy9LGt7kRwLtUEth5TvLYuC1cr0L0i8aVvkFsWNrVeZ_zzIOaRAino06vpx9TlLqU-CbBYcqL1AkunsEkiovl0uX1RiBvLkZPdbkysX664mztj13HRIeSZgokOgm6rwp8AIdb41r-226qmRzOfw36MvmOiVGUc5k_FhTKsfrdgBYqBTbXWt0xgVmmuIfMSshRMC3dfkQNtENSSYyGiY64k7D_3pke5gIdY-o56bEJWOxFiwHrvv2mR3ogG9fAUCwu0DAGcVY4vxb1IX5anZAq7-6ZBU06iQky-tjdSv0cmVDqkguN56JA84OihapRbFea95bjM_6O9kA_mxQFFvzrrtat75xDOTcCuGmUyzfBTBYVjP2x6lK5mFDYGFj6Nm4kWhoztNdaAvtuXHAEaICEiYLLgNB4SBrrsxvSfJmW2ACOXETFt0l0z6lAj1y5_bnUclefBlZmtp9J3PHMXZ1aCWm2GYfLq5kf0O33MWrFmzgkTXP0R0RDR8WYKS5n_b34YghlhrVqMz6Fi4WGcOwOrJbxzw7QRWXXIpDSUOCH4ICEeBFZtD8jJTPmoJdZgFBI12GUZrRnN9zw-cYHsuysRdCx2Tm_LA7_3WocJOZ9IoQ42lIeg-i7BOEwYQ3heCkdPHAXqmyrd4aOhRhfRIXh42yb7xGWx7AUfwbm8jxIe-WENvS70syR4ujcBsZhq-n13b4OeLBksVy2ABl4oe5Mhcc6AqewbqRNsR8siwfDF70VstuX6Y9lxStSd8joHy8Oi1AgEMpBR85igIhFUm5dnCVqiwCqSdMONMLZGAzh8CoytUBxXMPJjXtpYcqv2TxefxFRWkLY8d0eaR8pOns7JZ3wHjCGys7NACitACrlNjQ4ZFIY8OtwqdV-8MlpZcDN0-jCuyaHyrPTC_Sljg6vHM-1PICR-pCvDHODJXDv_GkIkR2DLCa8EoWNRALLKneYJhDqMmSNJAYevXkjSlLulX571v4ovHLvKHYb--oM9bjhkN5OavMdyBXlWWjIfP6ApV16hCKCshqACuWZs9vOAXeuj4RtTTs5NSZmyqh39KW_EwQ9qygeJraIEvjrVBBotY_42hvFiWsfRoHLZxBs3ehrWvovjhvqJPJMDEar5pYm4GpVUrqlvQnNHmGg_pzuJqwUKP33jktODsQRl0l0X0XhJNNSLLHMKIxyS5l33RikpWlcP5v8mtT-vuin0-vXoIz0_Ymp4J0P7yGujVfc6gA0QonphYYjIqiO84ojG4lV9BRuhd6xTJWbu9k1Rfi5pteiuVGcdpC5X-JPCl8AAoZxs1piWGxexstsb1YJmFJuFiQYfyCWyUhiaSG_px0kQk_Kok4EPiQ-OcVIzGyfwnNMOT_vMqgez0RmJL_O7LHVckmSs1Os8czP5OMHrt3k7pmIlGRENwvSSPlAB-VaPTz2mMlW6WQe9933E9o0-19ohrP3wzV9IbTuo4rlngt4l37TRvF2JMdJ5-fLT-RVWSd5RFDoeYKfmxplBDfIupBl5CQIMchzFmGaMq6eks3YtTlOIxSc1myOuwpHUjtXz530LBe--WRKwokLOZbuwygQCV-sYsUOFuPEhr1ESaaYNRFkjW9sXcrB1t.Ex4prN3h5RamnZ3o7RnS8A"

**Comment by acheong08** [comment]
Fixed
